# Generated by Django 5.0.6 on 2024-06-13 03:37

from django.db import migrations, models

def populate_roles(apps, schema_editor):                            
    Users_roles = apps.get_model('driver','Users_roles')
    obj = Users_roles(id='1')
    obj = Users_roles(name='User')
    obj.save()

    obj = Users_roles(id='2')
    obj = Users_roles(name='Driver')
    obj.save()
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RunPython(populate_roles),
    ]
