# Generated by Django 5.0.6 on 2024-06-13 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=35)),
                ('telp', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=30)),
                ('users_roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.users_roles')),
            ],
        ),
    ]
