# Generated by Django 5.0.6 on 2024-06-13 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_users_email_alter_users_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
