# Generated by Django 5.0.6 on 2024-06-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_trips_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=19),
        ),
    ]
